gain 25MB on nextdom-test image

diff --git a/install/postinst b/install/postinst
--- a/install/postinst
+++ b/install/postinst
@@ -3,15 +3,6 @@ set -e
 
 # Parameters
 DEBUG="/tmp/output.txt"
-VERT="\\033[1;32m"
-NORMAL="\\033[0;39m"
-ROUGE="\\033[1;31m"
-ROSE="\\033[1;35m"
-BLEU="\\033[1;34m"
-BLANC="\\033[0;02m"
-BLANCLAIR="\\033[1;08m"
-JAUNE="\\033[1;33m"
-CYAN="\\033[1;36m"
 declare -a DETAILS
 
 # Functions
@@ -71,6 +62,17 @@ print_log_ok() {
   fi
 }
 
+print_error(){
+  NORMAL="\\033[0;39m"
+  ROUGE="\\033[1;31m"
+
+  if [ 1 -eq "0${isdev}"  ] ; then
+      echo -e "${ROUGE}error${NORMAL}: $@"
+  else
+    echo -e "${ROUGE}error${NORMAL}: $@" >> ${LOG_DIRECTORY}/postinst.log
+  fi
+  exit 1
+}
 
 detect_dev_version(){
   isdev=0
@@ -176,8 +178,7 @@ step_nextdom_mysql_parameters() {
     return 0
   done
 
-  echo -e "${ROUGE}error: can't connect to mysql database${NORMAL}"
-  exit 1
+  print_error "can't connect to mysql database"
 }
 
 
@@ -188,16 +189,23 @@ step_nextdom_prerequisites_verification() {
   # Create apache configuration if missing
   local dstdir="/etc/apache2/sites-available"
   local srcdir="${WEBSERVER_HOME}/install/apache/"
+  local wwwdir="${WEBSERVER_HOME}"
 
   if [[ ! -d "${dstdir}" ]] ; then
-      echo -e "${ROUGE}error: apache2 not installed${NORMAL}"
-      exit 1
+      print_error "apache2 not installed"
   fi
+
+  # check that WEBSERVER_HOME is readable by www-data
+  sudo -u www-data test -r "${wwwdir}" || {
+    DETAILS+=("${wwwdir} not readable by www-data")
+    DETAILS+=("enabling compatibility mode, DocumentRoot targets /var/www/html")
+    wwwdir="/var/www/html/"
+  }
 
   for c_file in nextdom.conf nextdom-ssl.conf nextdom-common; do
     if [ ! -f ${dstdir}/${c_file} ] || [ 1 -eq "0${isdev}" ] ; then
       cp ${srcdir}/${c_file} ${dstdir}/${c_file} >> ${DEBUG} 2>&1
-      sed -i -e "s%\s+Define\s+wwwdir\s.*%Define wwwdir \"${WEBSERVER_HOME}\"%gI" ${dstdir}/${c_file} >> ${DEBUG} 2>&1
+      sed -i -e "s%\s+Define\s+wwwdir\s.*%Define wwwdir \"${wwwdir}\"%gI"         ${dstdir}/${c_file} >> ${DEBUG} 2>&1
       sed -i -e "s%\s+Define\s+logdir\s.*%Define logdir \"${LOG_DIRECTORY}\"%gI"  ${dstdir}/${c_file} >> ${DEBUG} 2>&1
       DETAILS+=("created file: ${dstdir}/${c_file}")
     fi
@@ -242,8 +250,7 @@ step_nextdom_apache_php() {
 
   service apache2 restart >> ${DEBUG} 2>&1 || {
     service apache2 restart >> ${DEBUG} 2>&1 || {
-      echo -e "${ROUGE}Ne peut redémarrer apache - Annulation${NORMAL}"
-      exit 1
+      print_error "unable to restart apache2"
     }
   }
 }
@@ -332,8 +339,7 @@ EOS
   if [ $(grep "www-data ALL=(ALL) NOPASSWD: ALL" /etc/sudoers | wc -l ) -eq 0 ]; then
       echo "www-data ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo) >/dev/null
       if [ $? -ne 0 ]; then
-          echo -e "${ROUGE}error: unable to add www-data to sudoers${NORMAL}"
-          exit 1
+          print_error "unable to add www-data to sudoers"
       fi
   fi
 }
@@ -347,8 +353,7 @@ step_nextdom_mysql_configuration() {
 
   service mysql stop >> ${DEBUG} 2>&1 || {
     service mysql stop >> ${DEBUG} 2>&1 || {
-      echo -e "${ROUGE}error: unable to stop mysql${NORMAL}"
-      exit 1
+      print_error "unable to stop mysql"
     }
   }
 
@@ -374,8 +379,7 @@ EOS
 
   service mysql start >> ${DEBUG} 2>&1 || {
     service mysql start >> ${DEBUG} 2>&1 || {
-      echo -e "${ROUGE}error: unable to start mysql${NORMAL}"
-      exit 1
+      print_error "unable to restart mysql"
     }
   }
 }
@@ -486,8 +490,7 @@ step_nextdom_mysql_populate() {
   mysql -uroot -h${MYSQL_HOSTNAME} ${HOSTPASS} -e "${QUERY}" >> ${DEBUG} 2>&1
 
   php ${WEBSERVER_HOME}/install/install.php mode=force >> ${DEBUG} 2>&1 || {
-    echo -e "${ROUGE}error: installation script failed${NORMAL}"
-    exit 1
+    print_error "nexdom installation script failed"
   }
 }
 
@@ -495,127 +498,132 @@ step_nextdom_mysql_populate() {
 # ======================================================================
 # Main
 
-LIB_DIRECTORY=/var/lib/nextdom
-LOG_DIRECTORY=/var/log/nextdom
-TMP_DIRECTORY=/tmp/nextdom
+main() {
+  LIB_DIRECTORY=/var/lib/nextdom
+  LOG_DIRECTORY=/var/log/nextdom
+  TMP_DIRECTORY=/tmp/nextdom
 
-while getopts "hi:p:d:r:u:z:L:l:t:" option; do
-  case "${option}" in
-    h)
-      usage
-      ;;
-    i)
-      MYSQL_HOSTNAME=${OPTARG}
-      ;;
-    z)
-      MYSQL_PORT=${OPTARG}
-      ;;
-    d)
-      MYSQL_NEXTDOM_DB=${OPTARG}
-      ;;
-    u)
-      MYSQL_NEXTDOM_USER=${OPTARG}
-      ;;
-    p)
-      MYSQL_NEXTDOM_PASSWD=${OPTARG}
-      ;;
-    r)
-      MYSQL_ROOT_PASSWD=${OPTARG}
-      ;;
-    L)
-      LOG_DIRECTORY=${OPTARG}
-      ;;
-    l)
-      LIB_DIRECTORY=${OPTARG}
-      ;;
-    t)
-      TMP_DIRECTORY=${OPTARG}
-      ;;
-    *)
-      usage
-      exit -1
-      ;;
-  esac
-done
-shift $((OPTIND-1))
+  while getopts "hi:p:d:r:u:z:L:l:t:" option; do
+    case "${option}" in
+      h)
+        usage
+        ;;
+      i)
+        MYSQL_HOSTNAME=${OPTARG}
+        ;;
+      z)
+        MYSQL_PORT=${OPTARG}
+        ;;
+      d)
+        MYSQL_NEXTDOM_DB=${OPTARG}
+        ;;
+      u)
+        MYSQL_NEXTDOM_USER=${OPTARG}
+        ;;
+      p)
+        MYSQL_NEXTDOM_PASSWD=${OPTARG}
+        ;;
+      r)
+        MYSQL_ROOT_PASSWD=${OPTARG}
+        ;;
+      L)
+        LOG_DIRECTORY=${OPTARG}
+        ;;
+      l)
+        LIB_DIRECTORY=${OPTARG}
+        ;;
+      t)
+        TMP_DIRECTORY=${OPTARG}
+        ;;
+      *)
+        usage
+        exit -1
+        ;;
+    esac
+  done
+  shift $((OPTIND-1))
 
-if [ $(id -u) != 0 ] ; then
-    echo "Les droits de super-utilisateur (root) sont requis pour installer NextDom"
-    echo "Veuillez lancer sudo $0 ou connectez-vous en tant que root, puis relancez $0"
-    exit 1
-fi
+  if [ $(id -u) != 0 ] ; then
+      echo "Les droits de super-utilisateur (root) sont requis pour installer NextDom"
+      echo "Veuillez lancer sudo $0 ou connectez-vous en tant que root, puis relancez $0"
+      exit 1
+  fi
 
-set_root $0
-prereq_create_dirs
-detect_dev_version
+  set_root $0
+  detect_dev_version
+  prereq_create_dirs
 
-print_log_in "step_nextdom_directory_layout ... "
-step_nextdom_directory_layout
-print_log_ok
 
-print_log_in "step_nextdom_assets ... "
-step_nextdom_assets
-print_log_ok
+  print_log_in "step_nextdom_directory_layout ... "
+  step_nextdom_directory_layout
+  print_log_ok
 
-print_log_in "step_nextdom_mysql_parameters ... "
-step_nextdom_mysql_parameters
-print_log_ok
+  print_log_in "step_nextdom_assets ... "
+  step_nextdom_assets
+  print_log_ok
 
-print_log_in "step_nextdom_var_www_html ... "
-step_nextdom_var_www_html
-print_log_ok
+  print_log_in "step_nextdom_mysql_parameters ... "
+  step_nextdom_mysql_parameters
+  print_log_ok
 
-print_log_in "step_nextdom_prerequisites_verification ... "
-step_nextdom_prerequisites_verification
-print_log_ok
+  print_log_in "step_nextdom_var_www_html ... "
+  step_nextdom_var_www_html
+  print_log_ok
 
-print_log_in "step_nextdom_apache_php ... "
-step_nextdom_apache_php
-print_log_ok
+  print_log_in "step_nextdom_prerequisites_verification ... "
+  step_nextdom_prerequisites_verification
+  print_log_ok
 
-print_log_in "step_nextdom_configuration ... "
-step_nextdom_configuration
-print_log_ok
+  print_log_in "step_nextdom_apache_php ... "
+  step_nextdom_apache_php
+  print_log_ok
 
-print_log_in "step_nextdom_mysql_configuration ... "
-step_nextdom_mysql_configuration
-print_log_ok
+  print_log_in "step_nextdom_configuration ... "
+  step_nextdom_configuration
+  print_log_ok
 
-print_log_in "step_nextdom_mysql_populate ... "
-step_nextdom_mysql_populate
-print_log_ok
+  print_log_in "step_nextdom_mysql_configuration ... "
+  step_nextdom_mysql_configuration
+  print_log_ok
 
-print_log_in "step_nextdom_crontab ... "
-step_nextdom_crontab
-print_log_ok
+  print_log_in "step_nextdom_mysql_populate ... "
+  step_nextdom_mysql_populate
+  print_log_ok
 
-print_log_in "step_nextdom_check ... "
-step_nextdom_check
-print_log_ok
+  print_log_in "step_nextdom_crontab ... "
+  step_nextdom_crontab
+  print_log_ok
 
-print_log_in "step_os_specific ... "
-step_os_specific
-print_log_ok
+  print_log_in "step_nextdom_check ... "
+  step_nextdom_check
+  print_log_ok
 
-print_log_in "step_nextdom_permissions ..."
-step_nextdom_file_permissions
-print_log_ok
+  print_log_in "step_os_specific ... "
+  step_os_specific
+  print_log_ok
 
-[[ -f /root/.mysqlroot ]] && rm -f /root/.mysqlroot
+  print_log_in "step_nextdom_permissions ..."
+  step_nextdom_file_permissions
+  print_log_ok
 
-if [ -f .git  ] ; then
-    cat - <<EOS
-Installation dir  : ${WEBSERVER_HOME}
+  [[ -f /root/.mysqlroot ]] && rm -f /root/.mysqlroot
 
-Database host     : ${MYSQL_HOSTNAME}
-Database port     : ${MYSQL_PORT}
-Database name     : ${MYSQL_NEXTDOM_DB}
-Database user     : ${MYSQL_NEXTDOM_USER}
-Database password : ${MYSQL_NEXTDOM_PASSWD}
+  if [ -f .git  ] ; then
+      cat - <<EOS
+  Installation dir  : ${WEBSERVER_HOME}
 
-> A self-signed SSL Certificate created in /etc/nextdom/ssl/
-> Please feel free to use another Certificate
+  Database host     : ${MYSQL_HOSTNAME}
+  Database port     : ${MYSQL_PORT}
+  Database name     : ${MYSQL_NEXTDOM_DB}
+  Database user     : ${MYSQL_NEXTDOM_USER}
+  Database password : ${MYSQL_NEXTDOM_PASSWD}
 
->>>>> COMPLETED <<<<<
+  > A self-signed SSL Certificate created in /etc/nextdom/ssl/
+  > Please feel free to use another Certificate
+
+  >>>>> COMPLETED <<<<<
 EOS
-fi
+  fi
+}
+
+main
